return {
  require("kickstart.plugins.vim-sleuth"),
  require("kickstart.plugins.gitsigns"),
  require("kickstart.plugins.which-key"),
  require("kickstart.plugins.telescope"),
  require("kickstart.plugins.lazydev"),
  require("kickstart.plugins.lspconfig"),
  require("kickstart.plugins.avante"),
  require("kickstart.plugins.conform"),
  require("kickstart.plugins.cmp"),
  require("kickstart.plugins.tokyonight"),
  require("kickstart.plugins.todo-comments"),
  require("kickstart.plugins.mini"),
  require("kickstart.plugins.treesitter"),
  require("kickstart.plugins.debug"),
  require("kickstart.plugins.java"),
}
